# Generated by Django 6.0.3 on 2026-03-21 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_ticket_status_alter_payment_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='parking.owner'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
