# Generated by Django 6.0.3 on 2026-03-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_ticket_owner_alter_slot_slot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='guard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.guard'),
        ),
    ]
