# Generated by Django 6.0.3 on 2026-03-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_ticket_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
