# Generated by Django 6.0.3 on 2026-03-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_payment_payment_ref_alter_guard_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
